discord:
  token: ${DISCORD_TOKEN}
  log_channel_id: 1453266242231337133
  allowed_channel_id: 1452952294445289483
  guild_id: 1451871483222823027

api:
  url: "https://falconsmmpanel.com/api/v2"
  key: ${API_KEY}

services:
  views: 2409
  likes: 2635
  shares: 2710
  follows: 2597

roles:
  free: "Free"
  bronze: "Bronze"
  silver: "Silver"

